# Generated by Django 5.0 on 2024-02-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
