# Generated by Django 5.0 on 2024-02-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
