# Generated by Django 5.0 on 2024-02-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='statuses_muted',
            field=models.BooleanField(default=False),
        ),
    ]
