# Generated by Django 5.0 on 2024-02-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_contact_statuses_muted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='archived',
        ),
        migrations.AddField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
