# Generated by Django 5.0 on 2024-04-19 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_chat_archived_contact_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chat')),
                ('name', models.CharField(max_length=72)),
                ('admins', models.ManyToManyField(related_name='group_chat', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.chat',),
        ),
    ]
