# Generated by Django 5.0 on 2024-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
