# Generated by Django 5.0 on 2024-05-18 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_admins',
            field=models.ManyToManyField(related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=72, null=True),
        ),
    ]
