# Generated by Django 5.0 on 2024-05-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_chat_chat_admins_chat_chat_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
