# Generated by Django 5.0 on 2024-05-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_delete_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_admins',
            new_name='admins',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat_name',
            new_name='name',
        ),
    ]
