# Generated by Django 5.0 on 2024-05-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_rename_chat_admins_chat_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chats/'),
        ),
    ]
