# Generated by Django 5.0 on 2024-08-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
