# Generated by Django 5.0 on 2024-08-13 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='starred',
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
