# Generated by Django 5.0 on 2024-08-22 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_message_starred_message_starred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='starred_by',
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
