# Generated by Django 5.0 on 2024-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_contact_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='Hey, I love this app 😍', max_length=150),
        ),
    ]
