# Generated by Django 5.0 on 2024-09-16 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
