# Generated by Django 5.0 on 2024-09-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_chat_archived_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='archived_by',
        ),
    ]
