# Generated by Django 5.0 on 2024-09-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_chat_archived_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='archived',
        ),
    ]
