# Generated by Django 5.0 on 2024-09-20 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_remove_contact_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
