# Generated by Django 5.0 on 2024-09-20 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_chat_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
