# Generated by Django 5.0 on 2024-10-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_chat_admins_alter_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='deleted_by',
        ),
    ]
