# Generated by Django 5.0 on 2024-12-08 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_message_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
