# Generated by Django 5.0 on 2024-12-27 23:59

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_remove_message_read_message_read_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('color', colorfield.fields.ColorField(default='#0dcaf0', image_field=None, max_length=25, samples=None)),
                ('prefered_background', models.CharField(choices=[('IMG', 'IMAGE'), ('CLR', 'COLOR')], default='CLR', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
