# Generated by Django 5.0 on 2024-12-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_chatbackground'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbackground',
            old_name='prefered_background',
            new_name='preferred_background',
        ),
    ]
