# Generated by Django 5.0 on 2024-12-29 22:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_rename_prefered_background_chatbackground_preferred_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbackground',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
