# Generated by Django 5.0 on 2024-12-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_alter_status_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='color',
        ),
    ]
