# Generated by Django 5.0 on 2024-12-30 00:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_remove_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
