# Generated by Django 5.0 on 2026-08-26 21:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbackground',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
